# Site settings
name: 天书奇谭随笔
email: 19975177@qq.com
author: Hanchun Liu
url: https://github.com/llhhccaa/
resume_site: https://github.com/llhhccaa/
github: https://github.com/llhhccaa/
baseurl: "/booktricks"
description: Actually, less is more!
meta_description: 刘韩春;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: llhhccaa
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : llhhccaa
    disqus :
        short_name : llhhccaa
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light